# Generated by Django 4.1.2 on 2022-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_L', models.CharField(max_length=255)),
                ('name_B', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=200)),
            ],
        ),
    ]
